# Generated by Django 5.2 on 2025-04-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadreport',
            name='location',
        ),
        migrations.AddField(
            model_name='roadreport',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roadreport',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roadreport',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='roadreport',
            name='location_type',
            field=models.CharField(choices=[('coordinates', 'Coordinates'), ('url', 'Location URL'), ('manual', 'Manual Entry')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='roadreport',
            name='location_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadreport',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='roadreport',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roadreport',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
